.ONESHELL:
SHELL = /bin/bash
.SHELLFLAGS += -e

MAIN_TARGET = $(FRR)
DERIVED_TARGET = $(FRR_PYTHONTOOLS) $(FRR_DBG) $(FRR_SNMP) $(FRR_SNMP_DBG)

$(addprefix $(DEST)/, $(MAIN_TARGET)): $(DEST)/% :

	# Build the package
	pushd ./frr

	# remove all diff and apply the patches
	git stash
	patch -p1  < ../patch/0001-zebra-kernel-level-graceful-restart.patch

	# clean up the previous build
	rm -rf debian
	rm -f frr*.tar.gz
	rm -f frr*.tar.xz
	rm -f frr*.dsc

	# make a dist tarball
	./bootstrap.sh
	./configure
	make dist

	# Create backports debian sources
	cp -a debianpkg debian
	make -f debian/rules backports

	# new directory to build the package 
	rm -rf frrpkg
	mkdir frrpkg
	cd frrpkg
	tar xf ../frr_*.orig.tar.gz
	cd frr*
	tar xf ../../frr_*sonic.debian8*.debian.tar.xz

	# build package
	dpkg-buildpackage -rfakeroot -b -us -uc
	cd ..
	mv $* $(DEST)/

	popd

